[2024-07-10 17:01:29,500] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spotify_to_s3.upload_to_s3 scheduled__2024-07-09T17:01:17.922331+00:00 [queued]>
[2024-07-10 17:01:29,566] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spotify_to_s3.upload_to_s3 scheduled__2024-07-09T17:01:17.922331+00:00 [queued]>
[2024-07-10 17:01:29,566] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 17:01:29,566] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-07-10 17:01:29,566] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 17:01:29,573] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-07-09 17:01:17.922331+00:00
[2024-07-10 17:01:29,576] {standard_task_runner.py:52} INFO - Started process 1252 to run task
[2024-07-10 17:01:29,577] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3', 'upload_to_s3', 'scheduled__2024-07-09T17:01:17.922331+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/upload_data_s3.py', '--cfg-path', '/tmp/tmpiieasvcy', '--error-file', '/tmp/tmpw_2crg7v']
[2024-07-10 17:01:29,578] {standard_task_runner.py:80} INFO - Job 7: Subtask upload_to_s3
[2024-07-10 17:01:29,585] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-10 17:01:29,603] {task_command.py:369} INFO - Running <TaskInstance: spotify_to_s3.upload_to_s3 scheduled__2024-07-09T17:01:17.922331+00:00 [running]> on host be84cfafb07d
[2024-07-10 17:01:29,636] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spotify_to_s3
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-07-09T17:01:17.922331+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-09T17:01:17.922331+00:00
[2024-07-10 17:01:29,679] {base_aws.py:447} WARNING - Unable to use Airflow Connection for credentials.
[2024-07-10 17:01:31,771] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_data_s3.py", line 85, in upload_to_s3
    s3.load_file(temp_file, 'spotify_data/spotify_data.json', bucket_name='project-rachman-2024', replace=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 541, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 288, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 758, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 415, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 732, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 751, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 107, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 180, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 121, in create_request
    operation_name=operation_model.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 358, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 229, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 212, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 95, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 167, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/auth.py", line 401, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2024-07-10 17:01:31,781] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_to_s3, task_id=upload_to_s3, execution_date=20240709T170117, start_date=20240710T170129, end_date=20240710T170131
[2024-07-10 17:01:31,793] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task upload_to_s3 (Unable to locate credentials; 1252)
[2024-07-10 17:01:31,802] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-10 17:01:31,824] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
