[2024-07-10 17:07:55,110] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spotify_to_s3.upload_to_s3 manual__2024-07-10T17:07:52.406561+00:00 [queued]>
[2024-07-10 17:07:55,208] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spotify_to_s3.upload_to_s3 manual__2024-07-10T17:07:52.406561+00:00 [queued]>
[2024-07-10 17:07:55,208] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 17:07:55,208] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-07-10 17:07:55,208] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 17:07:55,215] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-07-10 17:07:52.406561+00:00
[2024-07-10 17:07:55,217] {standard_task_runner.py:52} INFO - Started process 1677 to run task
[2024-07-10 17:07:55,219] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3', 'upload_to_s3', 'manual__2024-07-10T17:07:52.406561+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/upload_data_s3.py', '--cfg-path', '/tmp/tmpc3ccz8cm', '--error-file', '/tmp/tmp5_wwhxvj']
[2024-07-10 17:07:55,219] {standard_task_runner.py:80} INFO - Job 21: Subtask upload_to_s3
[2024-07-10 17:07:55,244] {task_command.py:369} INFO - Running <TaskInstance: spotify_to_s3.upload_to_s3 manual__2024-07-10T17:07:52.406561+00:00 [running]> on host be84cfafb07d
[2024-07-10 17:07:55,277] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spotify_to_s3
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-07-10T17:07:52.406561+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-10T17:07:52.406561+00:00
[2024-07-10 17:07:55,319] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2024-07-10 17:07:55,320] {base_aws.py:206} INFO - Credentials retrieved from login
[2024-07-10 17:07:59,925] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_data_s3.py", line 88, in upload_to_s3
    os.remove(temp_file)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/spotify_data.json'
[2024-07-10 17:07:59,938] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_to_s3, task_id=upload_to_s3, execution_date=20240710T170752, start_date=20240710T170755, end_date=20240710T170759
[2024-07-10 17:07:59,947] {standard_task_runner.py:97} ERROR - Failed to execute job 21 for task upload_to_s3 ([Errno 2] No such file or directory: '/tmp/spotify_data.json'; 1677)
[2024-07-10 17:07:59,982] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-10 17:08:00,007] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
